import type { MenuCategory } from '../types';

export const MENU_CATEGORIES: MenuCategory[] = [
  {
    id: 'food',
    name: 'Food',
    emoji: '🍽️',
    destination: 'kitchen',
    sortOrder: 0,
    items: [
      {
        id: 'pizza',
        name: 'Pizza',
        price: 12,
        emoji: '🍕',
        ingredients: ['Cheese', 'Tomato Sauce', 'Mushroom', 'Salami'],
        categoryId: 'food',
        destination: 'kitchen',
        sortOrder: 0,
      },
      {
        id: 'pasta',
        name: 'Pasta',
        price: 10,
        emoji: '🍝',
        ingredients: ['Pasta', 'Parmesan', 'Cream', 'Chicken'],
        categoryId: 'food',
        destination: 'kitchen',
        sortOrder: 1,
      },
      {
        id: 'bruschetta',
        name: 'Bruschetta',
        price: 7,
        emoji: '🥖',
        ingredients: ['Bread', 'Tomato', 'Basil', 'Olive Oil'],
        categoryId: 'food',
        destination: 'kitchen',
        sortOrder: 2,
      },
      {
        id: 'risotto',
        name: 'Risotto',
        price: 11,
        emoji: '🍚',
        ingredients: ['Rice', 'Parmesan', 'Butter', 'Mushroom'],
        categoryId: 'food',
        destination: 'kitchen',
        sortOrder: 3,
      },
    ],
  },
  {
    id: 'aperitif',
    name: 'Aperitif',
    emoji: '🥂',
    destination: 'bar',
    sortOrder: 1,
    items: [
      {
        id: 'aperol_spritz',
        name: 'Aperol Spritz',
        price: 7,
        emoji: '🍹',
        ingredients: ['Aperol', 'Prosecco', 'Soda Water'],
        categoryId: 'aperitif',
        destination: 'bar',
        sortOrder: 0,
      },
      {
        id: 'campari_soda',
        name: 'Campari Soda',
        price: 6,
        emoji: '🍸',
        ingredients: ['Campari', 'Soda Water'],
        categoryId: 'aperitif',
        destination: 'bar',
        sortOrder: 1,
      },
    ],
  },
  {
    id: 'alcohol',
    name: 'Alcohol',
    emoji: '🍷',
    destination: 'bar',
    sortOrder: 2,
    items: [
      {
        id: 'gin_tonic',
        name: 'Gin Tonic',
        price: 8,
        emoji: '🍸',
        ingredients: ['Gin', 'Tonic', 'Lemon'],
        categoryId: 'alcohol',
        destination: 'bar',
        sortOrder: 0,
      },
      {
        id: 'raboso',
        name: 'Raboso',
        price: 6,
        emoji: '🍷',
        ingredients: ['Raboso Wine'],
        categoryId: 'alcohol',
        destination: 'bar',
        sortOrder: 1,
      },
      {
        id: 'prosecco',
        name: 'Prosecco',
        price: 5,
        emoji: '🥂',
        ingredients: ['Prosecco'],
        categoryId: 'alcohol',
        destination: 'bar',
        sortOrder: 2,
      },
    ],
  },
  {
    id: 'non_alcoholic',
    name: 'Non-Alcoholic',
    emoji: '🥤',
    destination: 'bar',
    sortOrder: 3,
    items: [
      {
        id: 'coca_cola',
        name: 'Coca Cola',
        price: 3,
        emoji: '🥤',
        ingredients: [],
        categoryId: 'non_alcoholic',
        destination: 'bar',
        sortOrder: 0,
      },
      {
        id: 'still_water',
        name: 'Still Water',
        price: 2,
        emoji: '💧',
        ingredients: [],
        categoryId: 'non_alcoholic',
        destination: 'bar',
        sortOrder: 1,
      },
      {
        id: 'orange_juice',
        name: 'Orange Juice',
        price: 4,
        emoji: '🍊',
        ingredients: ['Fresh Orange'],
        categoryId: 'non_alcoholic',
        destination: 'bar',
        sortOrder: 2,
      },
    ],
  },
  {
    id: 'coffee',
    name: 'Coffee',
    emoji: '☕',
    destination: 'bar',
    sortOrder: 4,
    items: [
      {
        id: 'espresso',
        name: 'Espresso',
        price: 2,
        emoji: '☕',
        ingredients: ['Coffee'],
        categoryId: 'coffee',
        destination: 'bar',
        sortOrder: 0,
      },
      {
        id: 'cappuccino',
        name: 'Cappuccino',
        price: 3,
        emoji: '☕',
        ingredients: ['Coffee', 'Milk Foam'],
        categoryId: 'coffee',
        destination: 'bar',
        sortOrder: 1,
      },
      {
        id: 'caffe_latte',
        name: 'Caffè Latte',
        price: 3.5,
        emoji: '☕',
        ingredients: ['Coffee', 'Steamed Milk'],
        categoryId: 'coffee',
        destination: 'bar',
        sortOrder: 2,
      },
    ],
  },
  {
    id: 'desserts',
    name: 'Desserts',
    emoji: '🍰',
    destination: 'kitchen',
    sortOrder: 5,
    items: [
      {
        id: 'tiramisu',
        name: 'Tiramisù',
        price: 7,
        emoji: '🍰',
        ingredients: ['Mascarpone', 'Coffee', 'Cocoa', 'Ladyfingers'],
        categoryId: 'desserts',
        destination: 'kitchen',
        sortOrder: 0,
      },
      {
        id: 'panna_cotta',
        name: 'Panna Cotta',
        price: 6,
        emoji: '🍮',
        ingredients: ['Cream', 'Vanilla', 'Berry Sauce'],
        categoryId: 'desserts',
        destination: 'kitchen',
        sortOrder: 1,
      },
    ],
  },
];

// Flat lookup map: menuItemId -> MenuItem (with category info)
export const MENU_MAP = new Map(
  MENU_CATEGORIES.flatMap((cat) =>
    cat.items.map((item) => [item.id, item] as const),
  ),
);
